name: docs-ghpages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mtools e2fsprogs cryptsetup-bin dosfstools fdisk libparted-dev fakeroot

      - name: Install pip dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
        
      - name: Install packages
        run: |
          pip install -e embdgen-core
          pip install -e embdgen-cominit
          pip install -e embdgen-config-yaml

      - name: Build docs
        run: cd docs; make html

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

permissions:
  contents: read
  pages: write
  id-token: write
